title: Joseph Lewis - Data Scientist
email: josephgeorgelewis2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Joseph Lewis is a full-time Senior Data Scientist and outside of that is the author
  of a Data Science blog writing about reproducibility, AI and all things Data Science.
twitter_username: joelewisgl2000
github_username: josephlewisjgl
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joseph Lewis"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "Full Time Senior Data Scientist with 5+ years in Civil Service. BSc Data Science and Analytics."
  links:
    - label: "Medium"
      icon: "fab fa-fw fa-medium-m"
      url: "https://medium.com/@josephgeorgelewis2000"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joelewisgl2000"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/josephlewisjgl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/josephglewis/"
    - label: "Credly"
      icon: "fab fa-fw fa-id-badge"
      url: "https://www.credly.com/users/joe-lewis.f65547f7/badges"

footer:
  links:
    - label: "Medium"
      icon: "fab fa-fw fa-medium-m"
      url: "https://medium.com/@josephgeorgelewis2000"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joelewisgl2000"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/josephlewisjgl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/josephglewis/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
